DISTRO = "chrif"
DISTRO_NAME = "Chrif Reference DISTIBUTION"
DISTRO_CODENAME = "scarthgap"
DISTRO_VERSION = "1.0"
#Use one tmp dir 
TCLIBCAPPEND = ""
#Minimise GPLv3 packages
require conf/distro/include/no-gplv3.inc
#Enhance security options for CFLAGS/LDFLAGS
require conf/distro/include/security_flags.inc
DISTRO_FEATURES = "\
    acl \
    alsa \
    ext2 \
    ipv4 \
    ipv6 \
    pcmcia \
    usbgadget \
    usbhost \
    wifi \
    xattr \
    zeroconf \
    vfat \
    seccomp \
    "

#debug tweaks allow no pwd required and ssh server from dropbear cus it has small footprint 
IMAGE_FEATURES += "debug-tweaks ssh-server-dropbear"
IMAGE_INSTALL += " \
    wpa-supplicant \
    linux-firmware-rpidistro-bcm43455 \
"
NO_RECOMMENDATIONS = "1"
fdt addr ${fdt_addr} && fdt get value bootargs /chosen bootargs

test -n "${BOOT_DEVICE}" || setenv BOOT_DEVICE "A"
test -n "${BOOT_TRIES_LEFT}" || setenv BOOT_TRIES_LEFT 3
test -n "${BOOT_DEV}" || setenv BOOT_DEV "mmc 0:1"
test -n "${BOOT_MODE}" || setenv BOOT_MODE "valid"
setenv bootpart
setenv raucslot
if test "${BOOT_DEVICE}" "A" then
    setenv nextdevice "B"
    setenv next_bootpart "2"
elif test "${BOOT_DEVICE}" "B" then
    setenv nextdevice "A"
    setenv next_bootpart "1"
fi
if test "${BOOT_MODE}" = "TRIAL"; then
    if "${BOOT_TRIES_LEFT}" -gt 0; then
        setexpr BOOT_TRIES_LEFT ${BOOT_TRIES_LEFT} - 1
        echo "Booting in TRIAL mode, ${BOOT_TRIES_LEFT} tries left"
    else
        echo "No more tries left, switching to VALID mode"
        setenv BOOT_MODE "VALID"
        setenv BOOT_TRIES_LEFT 3
        setenv bootpart  "${next_bootpart}"
        steenv raucslot "${nextdevice}"
        setenv BOOT_DEVICE "${nextdevice}"
        
    fi
fi


  if test "x${bootpart}" != "x"; then
    # skip remaining slots
  elif test "x${BOOT_SLOT}" = "xA"; then
    if itest ${BOOT_A_LEFT} -gt 0; then
      setexpr BOOT_A_LEFT ${BOOT_A_LEFT} - 1
      echo "Found valid RAUC slot A"
      setenv bootpart "/dev/mmcblk0p2"
      setenv raucslot "A"
      setenv BOOT_DEV "mmc 0:2"
    fi
  elif test "x${BOOT_SLOT}" = "xB"; then
    if itest ${BOOT_B_LEFT} -gt 0; then
      setexpr BOOT_B_LEFT ${BOOT_B_LEFT} - 1
      echo "Found valid RAUC slot B"
      setenv bootpart "/dev/mmcblk0p3"
      setenv raucslot "B"
      setenv BOOT_DEV "mmc 0:3"
    fi
  fi
done

if test -n "${bootpart}"; then
  setenv bootargs "${bootargs} root=${bootpart} rauc.slot=${raucslot}"
  saveenv
else
  echo "No valid RAUC slot found. Resetting tries to 3"
  setenv BOOT_A_LEFT 3
  setenv BOOT_B_LEFT 3
  saveenv
  reset
fi

load ${BOOT_DEV} ${kernel_addr_r} boot/@@KERNEL_IMAGETYPE@@
if test ! -e mmc 0:1 uboot.env; then saveenv; fi;
@@KERNEL_BOOTCMD@@ ${kernel_addr_r} - ${fdt_addr}