DISTRO = "chrif"
DISTRO_NAME = "Chrif Reference DISTIBUTION"
DISTRO_CODENAME = "scarthgap"
DISTRO_VERSION = "1.0"
#Use one tmp dir 
#Minimise GPLv3 packages
require conf/distro/include/no-gplv3.inc
#Enhance security options for CFLAGS/LDFLAGS
require conf/distro/include/security_flags.inc
DISTRO_FEATURES = "\
    acl \
    alsa \
    ext2 \
    ipv4 \
    ipv6 \
    pcmcia \
    usbgadget \
    usbhost \
    wifi \
    xattr \
    zeroconf \
    vfat \
    seccomp \
"