DISTRO = "chrif"
DISTRO_NAME = "Chrif Reference DISTIBUTION"
DISTRO_CODENAME = "scarthgap"
DISTRO_VERSION = "1.0"
#Use one tmp dir 
TCLIBCAPPEND = ""
#Minimise GPLv3 packages
require conf/distro/include/no-gplv3.inc
#Enhance security options for CFLAGS/LDFLAGS
require conf/distro/include/security_flags.inc
INIT_MANAGER = "systemd"
DISTRO_FEATURES = "\
    ipv4 \
    ipv6 \
    pcmcia \
    usbgadget \
    usbhost \
    wifi \
    xattr \
    zeroconf \
    vfat \
    seccomp \
    "

#debug tweaks allow no pwd required and ssh server from dropbear cus it has small footprint 
IMAGE_FEATURES += "debug-tweaks ssh-server-dropbear"
IMAGE_INSTALL += " \
    wpa-supplicant \
    linux-firmware-rpidistro-bcm43455 \
"
NO_RECOMMENDATIONS = "1"
INHERIT += "cve-check"
INHERIT += "create-spdx"
