BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
            ${LAYERDIR}/recipes-*/*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*/*.bbappend"

BBFILE_COLLECTIONS += "chrif-distro"
BBFILE_PATTERN_chrif-distro = "^${LAYERDIR}/"
BBFILE_PRIORITY_chrif-distro = "10"

LAYERVERSION_chrif-distro = "1"
LAYERSERIES_COMPAT_chrif-distro = "scarthgap styhead walnasdf"
